### ISSUE TITLE
6.10 Crash

### ISSUE THREAD

**Issue by Thunderzapper** [notsamicc/Fortnite-Builds#19]
When i download 6.10 (6.10-CL-4476098) and run it, It gives me this error

``
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at FortniteLauncher.Program.<>c.<Main>b__3_0(Object sender, String data)
   at AsyncStreamReader.ReadCallback(IAsyncResult asyncResult)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.IO.Stream.ReadWriteTask.System.Threading.Tasks.ITaskCompletionAction.Invoke(Task completingTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   ``

I have an RX 6600 XT and a i5 11th gen if that helps.

**Comment by Thunderzapper** [comment]
nvm
